[package]
name = "themis"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
publish = false
license = "Apache-2.0 OR MIT"
description = "https://en.wikipedia.org/wiki/Themis"

[dependencies]
toml = "0.5.8"
serde = "1"
anyhow = "1"
semver = "1.0.4"
cargo_metadata = "0.14.1"
